### ISSUE TITLE
Implement API endpoints for setting page. Use Frontend UI for reference.

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#210]
Create new endpoints for managing the Settings page. This will involve setting up routes to handle CRUD operations for settings displayed in the application.

## Tasks
- [ ] Define the schema for Settings in PostgreSQL. Create a migration.
- [ ] Set up the Node.js server with the necessary routes.
- [ ] Implement the `GET /api/settings` endpoint to retrieve all settings.
- [ ] Implement the `POST /api/settings` endpoint to save a new setting.
- [ ] Implement the `PUT /api/settings/:id` endpoint to update an existing settings.
- [ ] Implement the `DELETE /api/settings/:id` endpoint to remove a settings(if necessary)
- [ ] Write test requests for each endpoint. Create a postman collection.

## Criteria
- All endpoints must be secured and only accessible to authorized users.

- The data returned should match the structure presented in the provided UI mockup.
- Integration tests should pass with 100% coverage for the new endpoints.
## Notes
- The backend logic should be implemented in accordance with the provided picture, ensuring consistency with the UI elements. Use the same code style and naming as for others controllers and endpoints.

https://www.figma.com/design/MLPbP1HM2L9ON6f88pHTee/User-onboarding?node-id=0-1&t=zfaJdBG4PYDSysBJ-1

**Comment by mr-loop-1** [comment]
The feature looks good and I can work on this. Please assign me.

**Comment by mr-loop-1** [comment]
I wanted to know more about this team feature. 
1. I add a person's email in my accounts's settings, then what would be the effect on dashboard of this invited person when they accept the invite. 
2. Can a person be in more than one team, say I am admin of 2 teams and member of 2 others

I assume that if point 2 is possible then the invited person would just have the team name in a list of teams they are part of somewhere on dashboard.

**Comment by mr-loop-1** [comment]
I wanted to know more about this team feature.

1. I assume a person can be in more than one team, say I am admin of 2 teams and member of 2 others.
2. I add a person's email in my accounts's settings, then what would be the effect on dashboard of this invited person when they accept the invite. Currently, Ui design is accroding to one team only

I think that if point 1 is possible then the invited person would have the team name in a list of teams they are part of somewhere on dashboard.

**Comment by erenfn** [comment]
@gorkem-bwl can provide you with more detailed information on this.

**Comment by gorkem-bwl** [comment]
@mr-loop-1 My answers inline. 

1. Currently there is only one team, and we'll implement different teams later. Currently you can focus with a single team where the UI doesn't have the capability to have additional teams to make things easier for implementation initially. Hence one person can be in a single team only.

2. When you invite a person, an invitation email is sent, and then when the user clicks on that email, [this Figma design be shown up](https://www.figma.com/design/MLPbP1HM2L9ON6f88pHTee/Onboarding?node-id=329-3818&t=4ut6x6dewOq7r7v9-1). Here is the screenshot: 

<img width="983" alt="Screenshot 2024-09-17 at 9 03 44 AM" src="https://github.com/user-attachments/assets/2ac43e52-ffd2-4eff-beb1-a800ed7f7990">

Upon registering, the user will be able to login to the dashboard immediately with the chosen password. 

Note that we are not going to implement social signins/signups at this stage. Let me know if there is anything unclear and/or needs elaboration

**Comment by mr-loop-1** [comment]
@gorkem-bwl yes having one team would be better initially for frontend. The way I am designing the routes and controllers, they are for multiple teams and will fit good with the initial one team plan.

There is one case that could cause a problem
- if there are two invites for the user, then which team is he going to be in
- how does a user be in a team, does create a by-default new team on sign up
- then if there is no invite and a user signs up, then what will they see

**Comment by mr-loop-1** [comment]
I have solution for pt 1 and pt 3,

Until a user has a team (like signing up directly), show them a page that lists invites received (for their mail). On that page, they can accept one of the invites and then it would become their team. From next log in, it would be the team dashboard only like in figma.
This would solve multiple invites too, as user can choose the team.

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl yes having one team would be better initially for frontend. The way I am designing the routes and controllers, they are for multiple teams and will fit good with the initial one team plan.
> 
> There are few doubts
> 
> * if there are two invites for the user, then which team is he going to be in
> * how does a user be in a team (say first user of a company), do they create a by-default new team on sign up
> * then if there is no invite and a user signs up, then what will they see

I think we better not think deeply about multiple teams for now. If we start implementing that, the design will considerably change. That is why I am a bit reluctant to add multiple teams feature.

The first user is an administrator always, and has the ability to invite others to the same team. When that first user signs up, he/she is assigned to the default team. 

The first user (admin) doesn't need any invites, as that user in fact is the user installing the app the first time. Any other user joining the same team is always invited. 

> * then if there is no invite and a user signs up, then what will they see

The no-invite-signup is only available for the first user. When that user signs up and then logs in, the first thing seen is the main dashboard itself.

HTH.

**Comment by mr-loop-1** [comment]
@gorkem-bwl that would simplify a lot of things. I will code with current designs only. I had actually implemented this team thing couple of time in work. Look forward to when we go for this.

**Comment by gorkem-bwl** [comment]
Yep - that makes sense, thank you for your contributions. 

If you need an extra design that is not there but required, just let me know and I'll add & link the corresponding Figma page here.
