### ISSUE TITLE
Refactor the "RadioButton" Component

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#66]
We need to enhance the existing "RadioButton" component to ensure it aligns with our application's design system and is fully reusable. @KenanTopal 

#### To-Do List:

- [ ] Create new branch from the `develop` branch specifically for this task. The branch name should match the issue title exactly for easy reference.
  
- [ ]  Delete/Modify/Create the "RadioButton" component to accept props for:
  - RadioButton text
  - RadioButton selection handler
  - RadioButton style variant
  - Additional styles or classes as needed

- [ ] Ensure the "RadioButton" component can accommodate various style variants, such as primary, secondary, etc., to match our design language.

- [ ] Confirm that the existing styles in `./RadioButtonStyles.css` are correctly implemented. Update the stylesheet as needed to support the new prop-based structure. Utilize constants for colors and styles, referencing the global color theme.

- [ ] Define the PropTypes for the "RadioButton" component, follow example:
  ```javascript
  RadioButton.propTypes = {
    label: PropTypes.string.isRequired,
    onChange: PropTypes.func.isRequired,
    variant: PropTypes.oneOf(['default', 'primary', 'secondary']),
    className: PropTypes.string,
  };
![RadioButton Component](https://github.com/bluewave-labs/bluewave-onboarding/assets/132397574/f1985c3b-5970-4fa5-a435-cd231c543048)
