### ISSUE TITLE
Develop the Avatar Component

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#67]
Create a new "Avatar" component that meet to our project design system and use across our application. @SevinjFeyzi 

#### To-Do List:

- [x] Start by creating a new branch from the `develop` branch for this task. Ensure the branch name same the issue title for  tracking purposes.
  
- [x] Create the "Avatar" component to accept props for:
  - Avatar image source
  - Avatar alt text
  - Avatar size (small, medium, large)
  - Additional styles or classes as necessary

- [x] The "Avatar" component should support different sizes and style variants, such as circular or with a border, to fit various UI contexts.

- [x] Verify that the existing styles in `./AvatarStyles.css` are applied correctly. Revise the stylesheet to accommodate the new prop-based structure. Use constants for dimensions and refer to the global color theme.

- [x] Clearly define the PropTypes for the "Avatar" component to ensure proper usage:
  ```javascript
  Avatar.propTypes = {
    src: PropTypes.string.isRequired,
    alt: PropTypes.string.isRequired,
    size: PropTypes.oneOf(['small', 'medium', 'large']),
    className: PropTypes.string,
  };
- [ ] Implement new Avatar component into right top menu ( frontend\src\components\Header\Header.jsx line:18)
![Avatar Component](https://github.com/bluewave-labs/bluewave-onboarding/assets/132397574/a7e3cfc5-0f16-43ea-a27b-c828ecdb0780)
