### ISSUE TITLE
Implement and integrate Checkbox component

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#74]
We need to refactor/create the Checkbox component to make it reusable for our application. Also implement props and ensure it can be integrated into our existing codebase.

## Tasks
- [x] Create a new branch from the `develop` branch named feature/Implement-and-integrate-Checkbox-component.
- [x] Update/create the Checkbox component to accept the following props:
  - `label`: to specify the text label associated with the checkbox.
  - `checked`: to determine whether the checkbox is initially checked.
  - `onChange`: to handle the change event when the checkbox is clicked.
  - `variant`: to define the checkbox style (e.g., primary, secondary).
  - `className`: to apply additional CSS classes.
  - `style`: to apply inline styles.
- [x] Ensure the component can handle different types of checkboxes, such as primary, secondary, etc.
- [x] Apply the existing styles from './CheckboxStyles.css' correctly and update if necessary to support the new prop-based structure.
- [x] Implement constants in the CSS file to use global color theme colors.
![image](https://github.com/bluewave-labs/bluewave-onboarding/assets/132397574/2aaab7c7-2b70-47b9-a018-e68640d85055)
