### ISSUE TITLE
Build the component TextField

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#86]
#### To-Do List:

- [x] Begin by creating a new branch from the `develop` branch. The branch name should be same of the task name feature/issue-number-description.

- [x] Build the component TextField (refactor existing , replace all outdated code in project related to TextField if necessary ).

- [x] Ensure that each component is customizable through props and use the project default styles and color themes.

- [x] Make sure to apply the project's default styles (`./TextFieldStyles.css`) to the components. Modify the CSS file to support the new components, using constants for colors and styles that align with the global theme.

- [x] Define PropTypes for each new component to ensure proper prop validation. 
- [x] Create test cases to verify that the components render correctly with different props.
![image](https://github.com/bluewave-labs/bluewave-onboarding/assets/132397574/39356c23-008b-4769-be3e-007ca31cd566)
https://www.figma.com/design/USQRG7Oacv7uXw8XkTPINq/Style-guide?node-id=0-1&t=U5agXmPAvJQe8j7c-0
