### ISSUE TITLE
Implement DropdownList component

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#93]
### Description:
The task involves creating a dropdown list component see the attached screenshot. 
The dropdown menu should allow users to select an action from the list.

The example actions should include 'No action', 'Open a URL', and 'Open a URL in a new tab', it can be any amount of ,make it reusable.
The components should be integrated with Material UI.

A component for the dropdown list.  Use Material UI's `Select` and `MenuItem` components for this.

### Tasks:
- [x] Create the DropdownList component.
- [x] Ensure that the component is reusable and its styles are consistent with the rest of the application.
- [ ] Integrate the component with Material UI and customize the styles as needed.
- [ ] Write tests for the DropdownList component to ensure it works as expected.
- [ ] Document the DropdownList component in the codebase for future reference.
- [x] Integrate new DropdownList component into our codebase. Refactor frontend\src\components\DropdownMenu\DropdownMenu.jsx

Figma example https://www.figma.com/design/MLPbP1HM2L9ON6f88pHTee/User-onboarding?node-id=0-1&t=p8i05HjYo4ihqe9j-0
![image](https://github.com/bluewave-labs/bluewave-onboarding/assets/132397574/c9c99126-9a6a-4cf2-9192-1fbd0cb517ef)

**Comment by erenfn** [comment]
You should apply the figma styles, it is not finished yet

**Comment by wlanhage** [comment]
I could look into this issue if its still not finished!

**Comment by erenfn** [comment]
Sure, there were a couple of things left, such as the blue outline instead of grey. We couldn't figure it out, as working with MUI styles can get messy.

**Comment by erenfn** [comment]
By the way, the most updated code is in develop. We first merge our PR's to develop. Also take a look at the latest PR about Dropdown List: #187

**Comment by erenfn** [comment]
Hey, how is this task going?

**Comment by wlanhage** [comment]
Hello, sorry for the delay. Had some school projects and intern interviews
last week and today. But will continue looking at it this week. I
understand if you also want to assign it to someone else, but its still in
my plans!

BR

Den fre 20 sep. 2024 kl 23:44 skrev erenfn ***@***.***>:
