### ISSUE TITLE
Create a new CustomLink component

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#97]
We need to create a new `CustomLink` component that aligns with our project's design system and can be reused across our application. This component should be versatile enough to handle different types of links, the "tertiary link with dashed lines" and "hovered tertiary link" .

## To-Do List
- [x] Create a new branch from the develop branch specifically for this task. Ensure that the branch name corresponds to this issue title for easy tracking. feature/97-create-a-new-customlink-component
- [x] Develop the `CustomLink` component to accept props such as:
  - Link text content
  - Link URL
  - Additional styles or classes as necessary
- [x] The `CustomLink` component should support various UI contexts by allowing different styles like dashed underline and solid underline when hovered. 
- [x] Use material UI  - import Link from '@material-ui/core/Link';
- [x] Create `./CustomLinkStyles.css` .
- [x] Define PropTypes .
- [x] Use default JavaScript parameters to set up default props 
- [x] Integrate this new CustomLink component into appropriate places within our application where links are required.
- [x] Create a minimum test using vitest for this component.

```javascript
CustomLink.propTypes = {
  text: PropTypes.string.isRequired,
  url: PropTypes.string.isRequired,
  className: PropTypes.string,
};
```

https://www.figma.com/design/USQRG7Oacv7uXw8XkTPINq/Style-guide?node-id=48-52733&t=nNFDTU9Sv5F8SXq9-0

![image](https://github.com/bluewave-labs/bluewave-onboarding/assets/132397574/79b21f7f-00b6-4633-836e-3d25ed89401a)
